#!/bin/bash

#SBATCH -J "GSidx"
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=40G

# Usage: 
# 	getindex GEDI GSLOC INDEXLOC FASTA GTF NAME

# Create GRAND-SLAM index in GSLOC using FASTA and GTF located in INDEXLOC
# index saved under ~/.gedi/genomic/${NAME}.oml

if [[ $# -ne 6 ]]; then
  echo "Usage: $0 [GEDI] [GSLOC] [INDEXLOC] [FASTA] [GTF] [NAME]"
  exit
fi

module load java/1.8.0_181

# executable
GEDI=$1
# GRAND-SLAM index directory - created if does not exists
GSLOC=$2
# location of index files (gtf/fasta)
INDEXLOC=$3
# name of fasta file
FASTA=$4
# name of gtf file
GTF=$5
# output name (GRAND-SLAM index)
NAME=$6

# fasta and gtf must be symlinked here
if [ ! -d "${GSLOC}" ]; then
 mkdir -p "${GSLOC}"
fi
cd "$GSLOC"
if [ ! -f "$FASTA" ]; then
 ln -s "${INDEXLOC}/${FASTA}" "$FASTA"
fi
if [ ! -f "$GTF" ]; then
 ln -s "${INDEXLOC}/${GTF}" "$GTF"
fi
# create index
"$GEDI" -e IndexGenome -s "$FASTA" -a "$GTF" -n "$NAME" -nokallisto -nobowtie -nostar -D
