#!/bin/bash

# Usage:
#       linkbams SAMPLELIST DIRLOC OUTPUT NAME

# Link BAM files to OUTPUT (create directory if does not exists),
# and create a list of files

if [[ $# -ne 4 ]]; then
  echo "Usage: $0 [SAMPLELIST] [DIRLOC] [OUTPUT] [NAME]"
  exit
fi

# location of BAM files
DIRLOC=$2
# GRAND-SLAM parent output directory
OUTPUT=$3
# output name (and results directory - created if does not exists)
NAME=$4
# bamlist - created
BAMLIST="${OUTPUT}/${NAME}.bamlist"

FILES=($DIRLOC/*)

if [ ! -d "${OUTPUT}/${NAME}" ]; then
 mkdir -p "${OUTPUT}/${NAME}"
fi

while IFS=" " read -r sample name
 do
  FILEN=$(printf '%s\n' "${FILES[@]}" | grep $sample | grep "sortdedup.bam$")
  NAME="${sample}_${name}.bam"
  if [[ "$name" = *0h* ]]; then
   NAME="${sample}_${name}_no4sU.bam"
  fi
  ln -s "$FILEN" "${OUTPUT}/$NAME"
  echo "$NAME" >> "$BAMLIST"
#   FILEN=$(printf '%s\n' "${FILES[@]}" | grep $sample | grep "sortdedup.bai$")
  FILEN=$(printf '%s\n' "${FILES[@]}" | grep $sample | grep "sortdedup.bam.bai$")
  NAME="${sample}_${name}.bai"
  if [[ "$name" = *0h* ]]; then
   NAME="${sample}_${name}_no4sU.bai"
  fi
  ln -s "$FILEN" "${OUTPUT}/$NAME"
 done < "$1"
