channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # python
  - python>=3.10
  - pysam
  - numpy
  - pandas
  - joblib
  - pyyaml
  - pip
  - setuptools
  # dependencies
  # comment/uncomment/add as per requirements
  - samtools # required
  #- salmon>=1.10 # transcript estimates only - broken
  - picard # pre-processing optional
  - subread # gene estimates only
  - bcftools # SNPs estimation
  - gffread # # transcript estimates only
  # R
  - r-base>=4.2.3
  - r-devtools
  - r-tidyverse
  - r-cowplot
  - r-gridextra
  - r-stringi
  - r-openxlsx
  - r-kernsmooth
  - r-magick
  - r-reshape2
  - r-plyr
  # extra R packages - post-processing/qc
  # comment/uncomment/add as per requirements
  - bioconductor-deseq2
  - bioconductor-ihw
  - bioconductor-glimma
  - bioconductor-topgo
  - bioconductor-org.hs.eg.db
  - bioconductor-biomart
  # development
  # comment/uncomment/add as per requirements
  #- pre_commit
  #- pytest
