#!/bin/bash

#SBATCH -J "bcftools"
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 24
#SBATCH --mem=50G

# Usage:
#       callsnps DIRLOC OUTPUT INDEXLOC FASTA NUMCPUS YML BAMLOC BAMLIST

# This script calls SNPs using BCFtools
# If BAMLIST is given, it will be used, otherwise will create a BAMLIST file
# from the samples (config)

if [[ $# -lt 7 && $# -gt 8 ]]; then
  echo "Usage: $0 [DIRLOC] [OUTPUT] [INDEXLOC] [FASTA] [NUMCPUS] [YML] [BAMLOC] <BAMLIST>"
  exit
fi


# BCFtools directory - created if does not exists
DIRLOC=$1
if [ ! -d "${DIRLOC}" ]; then
 mkdir -p "${DIRLOC}"
fi
cd "$DIRLOC"
# output name
OUTPUT=$2
# location of index (gtf/fasta)
INDEXLOC=$3
# name of fasta file
FASTA=$4
# number of CPUs
NUMCPUS=$5
# YML config
YML=$6
# location of BAM files
BAMLOC=$7
# BAMLIST is exists
if [ -z $8 ];
then
    # bamlist - created
    BAMLIST="${OUTPUT}.bamlist"
    SAMPLES=`grep -A100 'samples:' $YML | grep '^[[:space:]]' | cut -f2 -d':' | xargs`
    # bamlist must then be named accordingly
    for sample in $SAMPLES
     do
      BAM="$BAMLOC/$sample"
      echo "$BAM" >> "$BAMLIST"
      echo "Adding ${BAM} to BAMLIST..."
     done
else
    BAMLIST=$8
fi
echo "Using ${DIRLOC}/${BAMLIST} to estimate SNPs..."

if [ ! -f "$FASTA" ]; then
 ln -s "${INDEXLOC}/${FASTA}" "$FASTA"
fi


bcftools mpileup -Ou --threads ${NUMCPUS} -d 800 -f ${FASTA} -b ${BAMLIST} | bcftools call -mv -Ob -o "${OUTPUT}.bcf" && bcftools view -m2 -M2 --types snps -e'QUAL<40' "${OUTPUT}.bcf" -Ov -o "${OUTPUT}.snps.vcf"
