#!/bin/bash

#SBATCH -J "bcftools"
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 24
#SBATCH --mem=50G

# Usage: 
#       callsnps SAMPLELIST BAMLOC DIRLOC OUTPUT INDEXLOC FASTA NUMCPUS

# This script calls SNPs using BCFtools

if [[ $# -ne 7 ]]; then
  echo "Usage: $0 [SAMPLELIST] [BAMLOC] [DIRLOC] [OUTPUT] [INDEXLOC] [FASTA] [NUMCPUS]"
  exit
fi

# location of BAM files
BAMLOC=$2
# BCFtools directory - created if does not exists
DIRLOC=$3
# output name
OUTPUT=$4
# location of index (gtf/fasta)
INDEXLOC=$5
# name of fasta file
FASTA=$6
# number of CPUs
NUMCPUS=$7
# bamlist - created
BAMLIST="${OUTPUT}.bamlist"

if [ ! -d "${DIRLOC}" ]; then
 mkdir -p "${DIRLOC}"
fi
cd "$DIRLOC"
if [ ! -f "$FASTA" ]; then
 ln -s "${INDEXLOC}/${FASTA}" "$FASTA"
fi

# bamlist - create if SAMPLELIST exists, otherwise uses existing bamlist
# bamlist must then be named accordingly
if [ -f "$1" ]; then
 FILES=($BAMLOC/*)
 while IFS=" " read -r sample name
  do
   FILEN=$(printf '%s\n' "${FILES[@]}" | grep $sample | grep "sortdedup.bam$")
   echo "$FILEN" >> "$BAMLIST"
  done < "$1"
fi

bcftools mpileup -Ou --threads ${NUMCPUS} -d 800 -f ${FASTA} -b ${BAMLIST} | bcftools call -mv -Ob -o "${OUTPUT}.bcf" && bcftools view -m2 -M2 --types snps -e'QUAL<40' "${OUTPUT}.bcf" -Ov -o "${OUTPUT}.snps.vcf"

