#!/bin/bash

# Usage: 
# 	runbas2fastq RESLOC NUMCPUS

# Convert "split" BAM files back to FASTQ

if [[ $# -ne 3 ]]; then
  echo "Usage: $0 [RESLOC] [NUMCPUS]"
  exit
fi

# location of BAM files
RESLOC="$1/mapping"
# output - where to write FASTQ
OUTPUT="$1/raw"
# threads
NUMCPUS="-@$2"

if [ ! -d "${OUTPUT}" ]; then
 mkdir -p "${OUTPUT}"
fi

for f in $RESLOC/*.bam
 do  
  filename=$(basename -- "$f")
  mate1="${filename%%.*}_R1.fastq.gz"
  mate2="${filename%%.*}_R2.fastq.gz"
  samtools collate $NUMCPUS -O $f | samtools fastq $NUMCPUS -1 "${OUTPUT}/${mate1}" -2 "${OUTPUT}/${mate2}" -0 /dev/null -s /dev/null -n
 done
 
