
# I/O - full/absolute paths ---

# general input directory - sample list and config file
DATALOC=/prj/hIPSC_RNA_turnover_Naarmann/analysis/Krijgsveld_collaboration/pulseRTc/data
# space-separated sample_id sample_name
SAMPLELIST="$(DATALOC)/SAMPLELIST.TXT"
# config file for run-all-splbam
YML="$(DATALOC)/config.yaml"

# location of "original" BAM files - STAR output
BAMLOC_0=/prj/hIPSC_RNA_turnover_Naarmann/workflow/mapping
# location of BAM files after sorting/removing dups, ready for processing
# this is the location of your input BAM files to run the workflow (run-all-splbam)
# path to samples (config.yaml)
BAMLOC_1=/prj/hIPSC_RNA_turnover_Naarmann/analysis/Krijgsveld_collaboration/mapping
# location of results - parent directory where to write output of run-all-splbam
# created by run-all-splbam if does not exists
RESLOC := $(shell grep "parent" ${YML} | sed 's/parent://g' | xargs)
# annotations
INDEXLOC=../index/GRCh38.102.gtf
GTF=GRCh38.102.gtf
FASTA=GRCh38_102.fa

# tmp directory
TMPDIR=/scratch/global_tmp




# call ---

# call Python 
# w/o Slurm, use MKCMDPYTHON=python3
MKCMDPYTHON=srun
# call R
# w/o Slurm, use MKCMDR=Rscript
MKCMDR=srun
# call R - pulseR model fit
# w/o Slurm, use MKCMDRLONG=Rscript
MKCMDRLONG=srun -c 40 --mem=80GB -p long
# call bash scripts
# w/o Slurm, use MKCMDBASH=bash
# see also in scripts/pulser/utils.R
NUM_CPUS=24
MKCMDBASH=srun -c $(NUM_CPUS) --mem=50GB


# option call ---

# directory to write log files
LOGS=

# pulseRTc
# options (mostly Slurm-related) for run-all-splbam
ALL_OPTS=--use-slurm --num-cpus 40 --mem 100G --logging-level DEBUG --mail-user boileau@uni-heidelberg.de
# can be used to specify e.g. [--overwrite] or [--do-not-call] options
# for program options, use the config.yaml
RUN_OPTS=


# GRAND-SLAM
# executable
GEDI=/home/eboileau/install/GRAND-SLAM_2.0.5f/gedi
# name of index
INDEX_GS=GRCh38_102
# location of newly created index files - created if does not exists
INDEXLOC_GS=
# where to link BAM files and write output - created if does not exists
BAMLOC_GS=/prj/hIPSC_RNA_turnover_Naarmann/analysis/Krijgsveld_collaboration/SLAM/grand-slam/results
# name of output, e.g. time points used
OUTPUT_GS=all
# GRAND-SLAM options 
# ignore -no4sUpattern, file names now include pattern, use -full w/o -sparse" 
GSOPTS="-D -strandness Antisense -overlap Unique -trim5p 5 -trim3p 5 -full" 


# BCFtools
# output directory - created if does not exists
BCFLOC=
# name of output, e.g. time points used
OUTPUT_BCF=all


# subread - featureCounts
# output table name e.g. -0h-1h-2h-4h-6h-8h-16h.counts.tsv
OUTPUT_FC=


# pulseR
# location of results - parent directory where to write output of pulseR
# created by prep-fc/prep-salmon if does not exists
RESLOC_PULSER := $(shell grep "pulsedir" ${YML} | sed 's/pulsedir://g' | xargs)





